<?php

namespace AppBundle\Repository;

/**
 * ProductSubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
