<?php

namespace AppBundle\Repository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class ReceiptRepository extends \Doctrine\ORM\EntityRepository
{

    public function showReceiptsInSubcategory($id)
    {
        return $this->getEntityManager()->createQuery('SELECT r FROM AppBundle:Receipt r where r.subcategory = 1 order by r.name asc')->getResult();
    }
}
