<?php

namespace AppBundle\Repository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{



}
